// The JSFFI glue is generated by GHC's post-link.mjs and copied in by
// scripts/sync-engine.mjs. It exports a factory that is handed the object which
// will hold the instance's exports, and returns the import object GHC's runtime
// expects under `ghc_wasm_jsffi`.
declare function ghcWasmJsffi(exports: Record<string, unknown>): WebAssembly.ModuleImports
export default ghcWasmJsffi
