import { locale, type Locale } from "~/core/i18n"

/**
 * The Japan edition's own words.
 *
 * Core's dictionary is the type of core's dictionary, and core may not know
 * this edition exists, so an edition brings its words itself. The mechanism is
 * the one core already uses for the text it keeps outside the dictionary — the
 * starter journals, the demo — a table keyed by locale, read through a function.
 * `locale()` is a signal, so a label read at the moment it is drawn follows the
 * language being switched exactly as `t(...)` does.
 *
 * English is here as well as Japanese. Somebody keeping a Japanese company's
 * books does not necessarily read Japanese, and an edition that only spoke one
 * language would be deciding that for them. The terms of art keep their
 * Japanese beside the English where the English alone would be ambiguous —
 * "qualified invoice" is a phrase with a specific meaning here and a vaguer one
 * everywhere else.
 */

const en = {
  group: "Japan",
  nav: {
    chart: "Accounts",
    statements: "Statements",
    consumptionTax: "Consumption tax",
    fixedAssets: "Fixed assets",
    closing: "Year end",
  },
  layer: {
    fact: "In the books",
    factLead: "What hledger answered. The same in any country, and not affected by anything below.",
    judgement: "Under Japanese tax",
    judgementLead: "Classification and checks. These follow the rules of a year and the practice of a company, and can change without a single entry changing.",
    decided: "Worked out under the {{ rules }} rules",
    noJournal: "No journal open.",
    reading: "Reading…",
  },
  period: {
    year: "Financial year",
    startsIn: "Starts in",
    covers: "{{ from }} to {{ to }}",
    month: "Month {{ month }}",
  },
  chart: {
    lead: "What each account is, and where it is printed on a Japanese statement. Two separate facts, both written into the journal.",
    account: "Account",
    kind: "Kind",
    section: "Printed under",
    declared: "declared",
    assumed: "assumed from {{ from }}",
    unplaced: "nowhere yet",
    unrecognised: "not a heading: {{ said }}",
    inherited: "from {{ from }}",
    preset: "A chart to start from",
    presetLead: "Ordinary account directives, written into the journal. Nothing depends on taking them, and you can change or delete any of them afterwards.",
    presetAdd: "Add the {{ count }} that are not declared yet",
    presetNone: "Every account it offers is already declared.",
    writing: "Writing…",
    setSection: "Change where it is printed",
    unset: "—",
  },
  statements: {
    lead: "A balance sheet and an income statement, laid out the way a Japanese company's are. Every figure is hledger's; what happens here is the grouping.",
    balanceSheet: "Balance sheet",
    incomeStatement: "Income statement",
    asAt: "as at {{ date }}",
    over: "{{ from }} to {{ to }}",
    debits: "Debits",
    credits: "Credits",
    agree: "The two columns agree.",
    disagree: "The two columns do not agree — see the trial balance.",
    total: "Total",
    unplaced: "Not placed on this statement",
    unplacedLead: "Real accounts with no heading yet. They are shown here rather than left out of a total that would then look right.",
    empty: "Nothing to show for this year.",
  },
  section: {
    "current-assets": "Current assets",
    "fixed-assets": "Fixed assets",
    "deferred-assets": "Deferred assets",
    "current-liabilities": "Current liabilities",
    "long-term-liabilities": "Long-term liabilities",
    "shareholders-equity": "Shareholders' equity",
    "valuation-adjustments": "Valuation and translation adjustments",
    "subscription-rights": "Subscription rights to shares",
    revenue: "Net sales",
    "cost-of-sales": "Cost of sales",
    sga: "Selling, general and administrative expenses",
    "non-operating-income": "Non-operating income",
    "non-operating-expenses": "Non-operating expenses",
    "extraordinary-income": "Extraordinary income",
    "extraordinary-losses": "Extraordinary losses",
    "income-taxes": "Income taxes",
  },
  part: {
    assets: "Assets",
    liabilities: "Liabilities",
    equity: "Net assets",
  },
  running: {
    "gross-profit": "Gross profit",
    "operating-income": "Operating income",
    "ordinary-income": "Ordinary income",
    "pre-tax-income": "Income before income taxes",
    "net-income": "Net income",
  },
  tax: {
    lead: "What each band came to, from the tax tag on each posting. Totals of what is recorded — not a return.",
    band: "Band",
    postings: "Postings",
    recorded: "In the books",
    total: "Read as",
    within: "Tax within (for reference)",
    query: "hledger query",
    checkIt: "Put this query to hledger yourself and the same figure comes back.",
    entries: "{{ count }} entries read",
    included: "Books kept tax-inclusive",
    rounding: "Fractions {{ how }}",
    notWorkedOut: "Not worked out here",
    notChecked: "What the count of unclassified postings does not reach",
    sales: "of which sales",
    purchases: "of which purchases",
    unplaced: "on accounts hledger could not place",
    deductible: "of which deductible",
    notDeductible: "of which not deductible",
    notSaid: "{{ count }} postings with nothing said about deductibility, counted as deductible",
    deductLead: "Whether the tax on a purchase can be taken off what is owed is a second question, not a finer answer to the first: it turns on whether a qualified invoice was kept, whether a provider abroad is registered, and what the purchase was for. Write deduct:no on the posting, with the reason after a second colon if there is one.",
    reverseChargeLead: "A specified taxable purchase is one this company owes the tax on rather than the supplier. What becomes of it is not decidable from the entry: where the taxable sales ratio reaches 95 per cent, or a simplified basis applies, it is treated as never having happened — and that depends on a whole year's figures. The sales above are the material for that; the judgement is not made here.",
    bySideLead: "Three of the categories say nothing about which side of the books a figure was on, so totalling them together nets a sale against a purchase — and the ratio of taxable sales to all sales cannot be worked out from a figure like that. Which side it was on is in the account, so it is read from there.",
    said: {
      "taxable-base": "The taxable base, which is rounded down to the nearest thousand yen.",
      "tax-payable":
        "The tax payable, which depends on whether it is worked out by aggregation or by invoice.",
      "simplified-basis": "The simplified basis, and the transitional twenty-percent rule.",
      "national-and-local": "The split between national and local consumption tax.",
    },
    checkSaid: {
      "a purchase capitalised into an account these books have never classified — until one posting on that account is classified, nothing on it is asked about":
        "A purchase capitalised into an account these books have never classified. Nothing on that account is asked about until one posting on it is classified.",
      "accounts hledger could not place, which are in no count here at all":
        "Accounts hledger could not place. They are in no count here at all.",
    },
    rounded: { down: "rounded down", up: "rounded up", "half-up": "rounded to the nearest" },
    category: {
      "taxable-sale-10": "Taxable sales, 10%",
      "taxable-sale-8": "Taxable sales, 8% (reduced)",
      "taxable-purchase-10": "Taxable purchases, 10%",
      "taxable-purchase-8": "Taxable purchases, 8% (reduced)",
      "reverse-charge-10": "Reverse charge, 10% (specified taxable purchases)",
      "reverse-charge-8": "Reverse charge, 8% (specified taxable purchases)",
      "non-taxable": "Non-taxable",
      "tax-exempt": "Exempt (export)",
      "out-of-scope": "Out of scope",
    },
  },
  invoice: {
    title: "The paper behind each purchase",
    lead: "Whether the tax on a purchase can be deducted turns on what the supplier gave you and who they are — facts about a document rather than about the accounting. Nothing here is judged; the entries where the question arises are put in one place.",
    none: "No taxable purchases in this year.",
    date: "Date",
    description: "Description",
    partner: "With",
    status: "Invoice",
    evidence: "Document",
    nothingSaid: "nothing said",
    notAStatus: "not a status: {{ said }}",
    said: {
      qualified: "Qualified",
      "not-qualified": "Not qualified",
      unknown: "Unknown",
    },
  },
  assets: {
    lead: "What the company owns and is writing off. Kept beside the journal in a plain file that is only ever added to.",
    file: "Kept in {{ file }}",
    id: "Id",
    name: "Name",
    account: "Account",
    cost: "Cost",
    usefulLife: "Useful life",
    years: "{{ count }} years",
    method: "Method",
    inService: "In service",
    acquired: "Acquired",
    retired: "Retired",
    inUse: "In use",
    none: "No assets registered yet.",
    charge: "This year",
    switched: "revised rate",
    add: "Register an asset",
    adding: "Registering…",
    retire: "Dispose",
    correct: "Correct",
    cancel: "Cancel",
    why: "Why",
    retiringOne: "Disposing of {{ id }} — {{ name }}",
    correctingOne: "Correcting {{ id }} — {{ name }}",
    correctedOn: "Noticed on",
    correctLead: "Leave a box as it is to leave that detail as it is. A correction is a new line in the register; the line that was wrong stays where it is, and the register is what reading them in order comes to.",
    save: "Add to the register",
    method_: { "straight-line": "Straight line", "declining-balance": "Declining balance" },
    undecided: {
      method: "Not worked out here: {{ said }}. Enter this one by hand.",
      "useful-life": "{{ years }} years is outside the published table.",
      "acquired-before": "Bought on {{ acquired }}, before the rates from {{ from }} that these rules hold. Enter this one by hand.",
      cost: "The cost “{{ said }}” is not a figure.",
      "not-yet-in-service": "Not in use until {{ inService }}.",
      retired: "Disposed of on {{ on }}.",
      "retired-during-the-year": "Disposed of on {{ on }}. How the year of disposal is treated is your decision, so nothing is proposed.",
      "fully-written-off": "Nothing left but the memorandum value.",
    },
  },
  closing: {
    lead: "The entries a year is closed with. Nothing is written until you press — what you see is the text that would go into the journal.",
    depreciation: "Depreciation",
    depreciationLead: "Worked out from the register and from what the journal says has been written off already.",
    accruals: "Carried across the year end",
    accrualsLead: "There is no way to see from the books that a payment covers next year. Type the figure and this writes the entry the right way round.",
    kind: {
      "accrued-expense": "Accrued expense (未払費用)",
      "prepaid-expense": "Prepaid expense (前払費用)",
      "accrued-revenue": "Accrued revenue (未収収益)",
      "unearned-revenue": "Unearned revenue (前受収益)",
    },
    working: "Expense or revenue account",
    carried: "Account carrying it across",
    amount: "Amount",
    addRow: "Add another",
    propose: "Offer {{ count }} entries for review",
    nothing: "Nothing to offer yet.",
    offering: "Offering…",
    offered: "Offered — see the panel.",
    into: "Post depreciation to",
    expense: "Expense account",
    against: "Credited to",
    againstHint: "The asset's own account writes it down directly; an accumulated depreciation account leaves the cost standing.",
  },
  check: {
    errors: "Does not hold together",
    warnings: "Worth checking",
    none: "Nothing to report.",
    errorLead: "Something written here is not what somebody meant. Figures resting on it do not mean anything yet.",
    warningLead: "Places where a person has to decide. None of these is necessarily wrong.",
    entry: "entry {{ index }}",
    said: {
      "register-line": "Line {{ line }} of the register cannot be read: {{ why }}",
      "asset-unknown": "{{ id }} was {{ event }} on {{ at }}, but nothing acquired it.",
      "asset-account-unknown": "{{ id }} is posted to {{ account }}, which the journal does not have.",
      "asset-cost": "{{ id }} has a cost of “{{ said }}”, which is not a figure.",
      "asset-useful-life": "{{ id }} has a useful life of {{ years }} years, which the published table does not reach.",
      "asset-in-service-early": "{{ id }} was in service on {{ inService }}, before it was acquired on {{ acquiredAt }}.",
      "asset-commodity": "{{ id }} is recorded in {{ said }}; the journal writes figures in {{ declared }}.",
      "asset-method": "{{ id }} is written off by {{ said }}, which is not worked out here.",
      "asset-behind-schedule": "{{ id }}: the journal has written off {{ writtenOff }} where the schedule reaches {{ scheduled }}. A year may not have been posted.",
      "tax-unrecognised": "“{{ said }}” on {{ account }} is not one of the categories.",
      "deduct-unrecognised": "“{{ said }}” on {{ account }} is neither yes nor no, so nothing was read from it.",
      "tax-unmarked": "{{ account }} has nothing said about its treatment.",
      "invoice-unstated": "A taxable purchase with nothing recorded about the document behind it.",
      "invoice-number-shape": "“{{ said }}” is not shaped like a registration number (T and thirteen digits).",
      "account-unplaced": "{{ account }} has no heading, and none could be assumed.",
      "account-heading": "{{ account }} is declared under “{{ said }}”, which is not a heading.",
    },
  },
}

const ja: typeof en = {
  group: "日本会計",
  nav: {
    chart: "勘定科目",
    statements: "決算書",
    consumptionTax: "消費税",
    fixedAssets: "固定資産",
    closing: "決算整理",
  },
  layer: {
    fact: "会計事実",
    factLead: "hledger が答えたもの。どの国でも同じで、下の内容には左右されません。",
    judgementLead: "分類と確認。年度の税制と会社の実務に従うもので、仕訳が一つも変わらなくても変わります。",
    judgement: "日本税制での扱い",
    decided: "{{ rules }} の規定で計算",
    noJournal: "帳簿が開かれていません。",
    reading: "読み込み中…",
  },
  period: {
    year: "事業年度",
    startsIn: "開始月",
    covers: "{{ from }} 〜 {{ to }}",
    month: "{{ month }} 月",
  },
  chart: {
    lead: "各勘定科目が何であり、日本の決算書のどこに載るか。別々の二つの事実で、どちらも帳簿に書かれます。",
    account: "勘定科目",
    kind: "種類",
    section: "表示区分",
    declared: "宣言済み",
    assumed: "{{ from }} からの推定",
    unplaced: "未設定",
    unrecognised: "区分ではありません: {{ said }}",
    inherited: "{{ from }} から継承",
    preset: "出発点になる勘定科目",
    presetLead: "普通の account ディレクティブを帳簿に書くだけです。取り込まなくても何も困りませんし、後から自由に変更・削除できます。",
    presetAdd: "未宣言の {{ count }} 件を追加",
    presetNone: "提供する科目はすべて宣言済みです。",
    writing: "書き込み中…",
    setSection: "表示区分を変更",
    unset: "—",
  },
  statements: {
    lead: "日本の法人の様式で並べた貸借対照表と損益計算書。数字はすべて hledger のもので、ここでしているのは並べ替えだけです。",
    balanceSheet: "貸借対照表",
    incomeStatement: "損益計算書",
    asAt: "{{ date }} 現在",
    over: "{{ from }} 〜 {{ to }}",
    debits: "借方合計",
    credits: "貸方合計",
    agree: "貸借は一致しています。",
    disagree: "貸借が一致していません — 試算表を確認してください。",
    total: "合計",
    unplaced: "この決算書に載らない科目",
    unplacedLead: "表示区分が未設定の実在の科目です。合計から黙って外すと合計が正しく見えてしまうので、ここに出しています。",
    empty: "この年度に表示するものがありません。",
  },
  section: {
    "current-assets": "流動資産",
    "fixed-assets": "固定資産",
    "deferred-assets": "繰延資産",
    "current-liabilities": "流動負債",
    "long-term-liabilities": "固定負債",
    "shareholders-equity": "株主資本",
    "valuation-adjustments": "評価・換算差額等",
    "subscription-rights": "新株予約権",
    revenue: "売上高",
    "cost-of-sales": "売上原価",
    sga: "販売費及び一般管理費",
    "non-operating-income": "営業外収益",
    "non-operating-expenses": "営業外費用",
    "extraordinary-income": "特別利益",
    "extraordinary-losses": "特別損失",
    "income-taxes": "法人税等",
  },
  part: {
    assets: "資産の部",
    liabilities: "負債の部",
    equity: "純資産の部",
  },
  running: {
    "gross-profit": "売上総利益",
    "operating-income": "営業利益",
    "ordinary-income": "経常利益",
    "pre-tax-income": "税引前当期純利益",
    "net-income": "当期純利益",
  },
  tax: {
    lead: "各仕訳の tax タグから集計した区分別の金額。記帳額の合計であって、申告書ではありません。",
    band: "区分",
    postings: "仕訳行",
    recorded: "記帳額",
    total: "読み替え後",
    within: "内消費税相当額（参考）",
    query: "hledger クエリ",
    checkIt: "このクエリを自分で hledger に投げれば同じ数字が返ります。",
    entries: "{{ count }} 件の仕訳を読みました",
    included: "税込経理",
    rounding: "端数は{{ how }}",
    notWorkedOut: "ここでは算出しないもの",
    notChecked: "未分類の検出が届かないもの",
    sales: "うち売上側",
    purchases: "うち仕入側",
    unplaced: "hledger が種類を判定できない科目",
    deductible: "うち控除可",
    notDeductible: "うち控除不可",
    notSaid: "控除可否の記載がない仕訳行 {{ count }} 件 ── 控除可として数えています",
    deductLead: "仕入税額控除ができるかどうかは、区分の細分ではなく別の問いです ── 適格請求書を保存しているか、国外の提供者が登録しているか、何に使ったか、で決まります。控除できないものは posting に deduct:no を、理由があればコロンの後に書いてください。",
    reverseChargeLead: "特定課税仕入れは、供給者ではなくこの会社が納税義務を負うものです。どうなるかは仕訳からは決まりません ── 課税売上割合が95%以上、または簡易課税・2割特例が適用される課税期間は「なかったものとされる」ので、年度全体の数字次第です。上の売上はその判断材料で、判断自体はここではしません。",
    bySideLead: "非課税・免税・対象外の3区分は売上か仕入かを言わないので、合算すると売上と仕入が相殺されます ── その数字からは課税売上割合が出せません。どちらの側かは勘定科目が持っているので、そこから読みます。",
    said: {
      "taxable-base": "課税標準額（千円未満切捨て）",
      "tax-payable": "納付税額 ── 割戻し計算と積上げ計算のどちらによるかで変わります",
      "simplified-basis": "簡易課税、および2割特例",
      "national-and-local": "消費税と地方消費税の内訳",
    },
    checkSaid: {
      "a purchase capitalised into an account these books have never classified — until one posting on that account is classified, nothing on it is asked about":
        "これまで一度も分類されたことのない科目に資産計上された仕入 ── その科目の仕訳が一つ分類されるまで、何も問われません。",
      "accounts hledger could not place, which are in no count here at all":
        "hledger が種類を判定できなかった科目。ここのどの集計にも入りません。",
    },
    rounded: { down: "切り捨て", up: "切り上げ", "half-up": "四捨五入" },
    category: {
      "taxable-sale-10": "課税売上 10%",
      "taxable-sale-8": "課税売上 8%（軽減）",
      "taxable-purchase-10": "課税仕入 10%",
      "taxable-purchase-8": "課税仕入 8%（軽減）",
      "reverse-charge-10": "リバースチャージ 10%（特定課税仕入れ）",
      "reverse-charge-8": "リバースチャージ 8%（特定課税仕入れ）",
      "non-taxable": "非課税",
      "tax-exempt": "免税（輸出等）",
      "out-of-scope": "対象外（不課税）",
    },
  },
  invoice: {
    title: "各仕入の証憑",
    lead: "仕入税額控除ができるかどうかは、相手先が何を発行したか・誰であるかで決まります ── 会計ではなく書類の事実です。ここでは判定はしません。その問いが立つ仕訳を一箇所に並べるだけです。",
    none: "この年度に課税仕入はありません。",
    date: "日付",
    description: "摘要",
    partner: "相手先",
    status: "インボイス",
    evidence: "証憑",
    nothingSaid: "記載なし",
    notAStatus: "区分ではありません: {{ said }}",
    said: {
      qualified: "適格",
      "not-qualified": "適格でない",
      unknown: "不明",
    },
  },
  assets: {
    lead: "会社が持ち、償却しているもの。帳簿の隣の、追記しかしない平文ファイルで管理します。",
    file: "{{ file }} に保存",
    id: "資産番号",
    name: "名称",
    account: "勘定科目",
    cost: "取得価額",
    usefulLife: "耐用年数",
    years: "{{ count }} 年",
    method: "償却方法",
    inService: "事業供用日",
    acquired: "取得日",
    retired: "除却日",
    inUse: "使用中",
    none: "登録された資産はまだありません。",
    charge: "当期償却額",
    switched: "改定償却率",
    add: "資産を登録",
    adding: "登録中…",
    retire: "除却",
    correct: "訂正",
    cancel: "やめる",
    why: "理由",
    retiringOne: "{{ id }} — {{ name }} を除却",
    correctingOne: "{{ id }} — {{ name }} を訂正",
    correctedOn: "訂正日",
    correctLead: "空欄の項目はそのままです。訂正は台帳への追記で、間違っていた行はそのまま残ります ── 台帳は行を順に読んだ結果です。",
    save: "台帳に追加",
    method_: { "straight-line": "定額法", "declining-balance": "定率法" },
    undecided: {
      method: "ここでは計算しません: {{ said }}。この資産は手入力してください。",
      "useful-life": "耐用年数 {{ years }} 年は公表されている表の範囲外です。",
      "acquired-before": "取得日 {{ acquired }} は、この規定が持つ {{ from }} 以後の率の対象外です。手入力してください。",
      cost: "取得価額「{{ said }}」が数値として読めません。",
      "not-yet-in-service": "{{ inService }} まで事業供用されていません。",
      retired: "{{ on }} に除却済みです。",
      "retired-during-the-year": "{{ on }} に除却されています。除却年度の扱いは会社の判断なので、提案しません。",
      "fully-written-off": "備忘価額を残して償却済みです。",
    },
  },
  closing: {
    lead: "年度を締めるための仕訳です。押すまで何も書き込まれません — 表示されているのは実際に帳簿へ入る文面そのものです。",
    depreciation: "減価償却",
    depreciationLead: "台帳と、帳簿がすでに償却済みだと言っている額から計算します。",
    accruals: "期をまたぐもの",
    accrualsLead: "支払いが翌期分を含むかどうかは帳簿からは分かりません。金額を入力すれば、正しい向きで仕訳を作ります。",
    kind: {
      "accrued-expense": "未払費用",
      "prepaid-expense": "前払費用",
      "accrued-revenue": "未収収益",
      "unearned-revenue": "前受収益",
    },
    working: "費用・収益の科目",
    carried: "期をまたぐ科目",
    amount: "金額",
    addRow: "行を追加",
    propose: "{{ count }} 件を提案する",
    nothing: "提案できるものがありません。",
    offering: "提案中…",
    offered: "提案しました — パネルを確認してください。",
    into: "減価償却の記帳先",
    expense: "費用の科目",
    against: "貸方の科目",
    againstHint: "資産の科目に直接入れると簿価が下がります（直接法）。減価償却累計額に入れると取得価額が残ります（間接法）。",
  },
  check: {
    errors: "成立していないもの",
    warnings: "確認した方がよいもの",
    none: "報告することはありません。",
    errorLead: "書かれている内容が意図したものになっていません。これに乗る数字は、まだ意味を持ちません。",
    warningLead: "人が判断するところです。どれも間違いとは限りません。",
    entry: "仕訳 {{ index }}",
    said: {
      "register-line": "台帳の {{ line }} 行目が読めません: {{ why }}",
      "asset-unknown": "{{ id }} が {{ at }} に {{ event }} とありますが、取得の記録がありません。",
      "asset-account-unknown": "{{ id }} の科目 {{ account }} が帳簿にありません。",
      "asset-cost": "{{ id }} の取得価額「{{ said }}」が数値として読めません。",
      "asset-useful-life": "{{ id }} の耐用年数 {{ years }} 年は公表されている表の範囲外です。",
      "asset-in-service-early": "{{ id }} の事業供用日 {{ inService }} が取得日 {{ acquiredAt }} より前です。",
      "asset-commodity": "{{ id }} は {{ said }} で記録されていますが、帳簿の通貨は {{ declared }} です。",
      "asset-method": "{{ id }} の償却方法 {{ said }} はここでは計算しません。",
      "asset-behind-schedule": "{{ id }}: 帳簿の償却累計は {{ writtenOff }} ですが、計算上は {{ scheduled }} です。未計上の年度があるかもしれません。",
      "tax-unrecognised": "{{ account }} の「{{ said }}」は税区分ではありません。",
      "deduct-unrecognised": "{{ account }} の「{{ said }}」は yes でも no でもないので、何も読み取っていません。",
      "tax-unmarked": "{{ account }} に税区分が書かれていません。",
      "invoice-unstated": "課税仕入ですが、証憑についての記録がありません。",
      "invoice-number-shape": "「{{ said }}」は登録番号の形式（T＋13桁）ではありません。",
      "account-unplaced": "{{ account }} に表示区分がなく、推定もできません。",
      "account-heading": "{{ account }} の「{{ said }}」は表示区分ではありません。",
    },
  },
}

const WORDS: Readonly<Record<Locale, typeof en>> = { en, ja }

/** The words, in whichever language the screens are speaking. */
export const words = (): typeof en => WORDS[locale()]

/**
 * The words of one named language, for a test to hold them against the code.
 *
 * A sentence missing in one language and present in the other is a blank on
 * somebody's screen, and `typeof en` catches only a key that is absent — not one
 * that was added to a list the words are read by. See `tests/jp.test.ts`.
 */
export const wordsIn = (which: Locale): typeof en => WORDS[which]

/**
 * A sentence with its blanks filled, the way core's translator fills them.
 *
 * Written out here rather than borrowed because core's translator is bound to
 * core's dictionary. It is four lines and it keeps this edition from needing a
 * second i18n library to say one thing.
 */
export const filled = (template: string, values: Readonly<Record<string, string | number>>): string =>
  template.replace(/\{\{\s*(\w+)\s*\}\}/g, (whole, name: string) => {
    const value = values[name]
    return value === undefined ? whole : String(value)
  })
